### ISSUE TITLE
Tracker issue for web pages moving to new UI

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#411]
Following are pages that have to be applied with new UI. Some of them have complicated and common operations and they could be tracked in separate dedicated issue.

- [ ] The master template
  - [ ] Menubar
  - [ ] Link action: Bookmark this page
  - [ ] Show link for User Guide and other links configured in settings module
  - [ ] Quick search
  - [ ] Link of Advanced Search
- [ ] Login page
  - [ ] Single login with username and password
  - [ ] Login with enabled social authentications
- [ ] Home page
  - [ ] Basic Information
  - [ ] Bookmarks
  - [ ] Recent
- [ ] Pages under menu PLANNING
  - [ ] Search plans ("My plans" moves to this page)
  - [ ] New plan
- [ ] Pages under menu TESTING
  - [ ] Search runs ("My runs" moves to this page)
  - [ ] Search cases
  - [ ] New case
- [ ] Pages under menu ENVIRONMENT
  - [ ] Groups
  - [ ] Properties
- [ ] Pages under menu REPORTING
  - [ ] Overall
  - [ ] Custom
    - [ ] Custom detail page
  - [ ] Testing report
    - [ ] Case runs report
- [ ] Pages under menu ADMIN
- [ ] Attachment page
- [ ] Test plan pages
  - [ ] Create new test plan
  - [ ] Plan page (!!! Lots of interaction operation need to be rewritten.)
  - [ ] Clone Plan
- [ ] Test case pages
  - [ ] Create new test case
  - [ ] Case page (!!! Lots of interaction operation need to be rewritten.)
  - [ ] Clone cases
  - [ ] Clone case (might share template with "Clone Cases")
- [ ] Test run pages
  - [ ] Create new test run
  - [ ] Run page (!!! Lots of interaction operation need to be rewritten.)
  - [ ] Clone run
- [ ] The master template
  - [ ] Menubar
  - [ ] Link action: Bookmark this page
  - [ ] Show link for User Guide and other links configured in settings module
  - [ ] Quick search
  - [ ] Link of Advanced Search
- [ ] Login page
  - [ ] Single login with username and password
  - [ ] Login with enabled social authentications
- [ ] Home page
  - [ ] Basic Information
  - [ ] Bookmarks
  - [ ] Recent
- [ ] Pages under menu PLANNING
  - [ ] Search plans ("My plans" moves to this page)
  - [ ] New plan
- [ ] Pages under menu TESTING
  - [ ] Search runs ("My runs" moves to this page)
  - [ ] Search cases
  - [ ] New case
- [ ] Pages under menu ENVIRONMENT
  - [ ] Groups
  - [ ] Properties
- [ ] Pages under menu REPORTING
  - [ ] Overall
  - [ ] Custom
    - [ ] Custom detail page
  - [ ] Testing report
    - [ ] Case runs report
- [ ] Pages under menu ADMIN
- [ ] Attachment page
- [ ] Test plan pages
  - [ ] Create new test plan
  - [ ] Plan page (!!! Lots of interaction operation need to be rewritten.)
  - [ ] Clone Plan
- [ ] Test case pages
  - [ ] Create new test case
  - [ ] Case page (!!! Lots of interaction operation need to be rewritten.)
  - [ ] Clone cases
  - [ ] Clone case (might share template with "Clone Cases")
- [ ] Test run pages
  - [ ] Create new test run
  - [ ] Run page (!!! Lots of interaction operation need to be rewritten.)
  - [ ] Clone run
